### ISSUE TITLE
Incorrect advance width of .tf, features removed

### ISSUE THREAD

**Issue by domija** [domija/Aboreto#2]
Hi @emmamarichal,

First of all, thank you for the production.
I've took a bit deeper look at the forked font and I've noticed few issues:
- Width of tabular figures is not consistent => eight.tf and four.tf have incorrect advance width of 568, 600 respectively — should instead be 582 for all tabular figures
- Some locl features, which I believe are useful, were removed => the feature for languages utilizing capital I with dot was omitted — since the font only contains uppercase, when the languge is TRK | KAZ | TAT | AZE and lowercase "i" with dot is pressed, it should automatically convert to capital I with dot "İ" (  sub i by Idotaccent; ). Right now it just gets converted to normal capital I, which is incorrect. (I wanted to handle the correct mapping inside the font, so that the user doesn't have to select that the written text is UPPERCASE only)
- Locl for I_J_Acute was omitted, not sure whether it is a necessity, however some articles say that when the selected language is NLD | FLE and the users types I with acute followed by J, the J should get also acute
![features](https://user-images.githubusercontent.com/36168990/174493694-ee20d004-77b6-45c3-bf3c-0f4015da08d4.PNG)

Thanks

**Comment by domija** [comment]
(Unfortunately as the source files were modified to .glyphs I cannot propose the modified source file, since FontLab's support for .glyphs file is not sufficient)

**Comment by domija** [comment]
Another issue that I have registered is that some kerning pairs were not generated, for example kerning for L and W is missing completly. The fonts generated from the .ufo source files (in the 'old' folder) contain the data, which means that it had to be lost during the production phase.

**Comment by emmamarichal** [comment]
Hi @domija!
Thanks for reporting that, I'll take a look thursday and make you a new PR with the bugs corrected.
Don't hesitate to comment this issue if you see something else in the meantime.
Cheers!

**Comment by domija** [comment]
Thanks for the response,
I have also noticed that for some reason, some kerning exceptions were lost. (Could be due to Fontlab handling them differently? As it seems that the generated .ufo file doesn't contain them as well.)

For some strange reason kerning between L and W (however for example V has correct kerning) is not being recognised in Illustrator (has value of 0), even though the font editor shows it. Regenerated .otf from .vfc source (fontlab native) doesn't exhibit this issue. The correct value should be **-60**. Only the pair Lcaron and V group (V + W + W with accents) should have kerning of **0** to prevent collision.

If there is some better way for me to export the data from Fontlab, please let me know.

Thanks,
Dominik
